### ISSUE TITLE
Cron have dependency pulling moment. 

### ISSUE THREAD

**Issue by LimitR** [fastify/.github#12]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.20.2

### Plugin version

1.1.2

### Node.js version

14.17.6

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Cron have dependency pulling moment. 

Please delete, you can replace all this functionality in 15 seconds.

### Steps to Reproduce

```shell
npm uninstall moment
```

### Expected Behavior

Cron have dependency pulling moment. 

Please delete, you can replace all this functionality in 15 seconds

**Comment by climba03003** [comment]
I don't know what is the actual problem for your issue?

**Comment by zekth** [comment]
> Please delete, you can replace all this functionality in 15 seconds

PRs are welcome

**Comment by LimitR** [comment]
> I don't know what is the actual problem for your issue.

Such a libs should definitely be removed from dependencies.

This is bullshit :/

**Comment by kibertoad** [comment]
PR is welcome :)

**Comment by climba03003** [comment]
I will just close this issue because I don't know  where do we use `cron`. All of the plug-in I remember do not have direct dependency of `cron`.
Please correct me or provide any useful information from an issue.

**Comment by jsumners** [comment]
They will not be correcting anyone. Their attitude is unacceptable.
