### ISSUE TITLE
update security issue template

### ISSUE THREAD

**Issue by climba03003** [fastify/.github#16]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The current security template do not match the new policy.
It should be either updated or removed.

**Comment by Fdawgs** [comment]
Where is the new policy?

**Comment by climba03003** [comment]
https://github.com/fastify/.github/blob/main/SECURITY.md

**Comment by climba03003** [comment]
Resolved by #19
