### ISSUE TITLE
Skip macos-latest for Node.js v14 and v16 in the 3.x line

### ISSUE THREAD

**Issue by mcollina** [fastify/.github#37]
GHA updated macos-latest to be an ARM platform. However this broke all our CI runs for all plugins because there are no arm build for Node v14 and v16.

The solution is to skip macos-latest and those versions of Node.js everywhere in the 3.x line (which is what we use everywhere).

**Comment by mcollina** [comment]
cc @simoneb

**Comment by simoneb** [comment]
Sent a proposed change here, check it out https://github.com/fastify/workflows/pull/127

**Comment by Fdawgs** [comment]
closed by https://github.com/fastify/workflows/pull/127 and https://github.com/fastify/workflows/pull/128
