### ISSUE TITLE
Add a minimal reproduction 

### ISSUE THREAD

**Issue by mcollina** [fastify/.github#5]
https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md is a guide we could adapt link from our own docs.

**Comment by mcollina** [comment]
cc @fastify/core

**Comment by RafaelGSS** [comment]
Might https://github.com/fastify/.github/blob/master/.github/ISSUE_TEMPLATE/bug.md is a good one to have. There are some other locations?

**Comment by jsumners** [comment]
I am on board with this. We should include a list of issues from our own repositories that we think have exemplified how to report issues.

**Comment by mcollina** [comment]
> Might https://github.com/fastify/.github/blob/master/.github/ISSUE_TEMPLATE/bug.md is a good one to have. There are some other locations?

yes!!!

**Comment by jsumners** [comment]
https://github.com/sindresorhus/.github/blob/main/contributing.md
